"""initial PMO schema"""
from alembic import op
import sqlalchemy as sa
revision='0001_initial';down_revision=None;branch_labels=None;depends_on=None

def upgrade():
    op.create_table('users',sa.Column('id',sa.String(36),primary_key=True),sa.Column('username',sa.String(80),unique=True,index=True),sa.Column('full_name',sa.String(160),nullable=False),sa.Column('password_hash',sa.String(255),nullable=False),sa.Column('role',sa.String(40),nullable=False,server_default='viewer'),sa.Column('active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('last_login',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('records',sa.Column('id',sa.String(36),primary_key=True),sa.Column('module',sa.String(120),nullable=False,index=True),sa.Column('external_id',sa.String(160),index=True),sa.Column('data',sa.JSON(),nullable=False),sa.Column('version',sa.Integer(),nullable=False,server_default='1'),sa.Column('status',sa.String(40),nullable=False,server_default='draft'),sa.Column('created_by',sa.String(36),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('audit_logs',sa.Column('id',sa.String(36),primary_key=True),sa.Column('user_id',sa.String(36),nullable=False,index=True),sa.Column('action',sa.String(80),nullable=False,index=True),sa.Column('entity_type',sa.String(80),nullable=False),sa.Column('entity_id',sa.String(36)),sa.Column('before_data',sa.JSON()),sa.Column('after_data',sa.JSON()),sa.Column('ip_address',sa.String(64)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,index=True))
    op.create_table('approvals',sa.Column('id',sa.String(36),primary_key=True),sa.Column('record_id',sa.String(36),nullable=False,index=True),sa.Column('requested_by',sa.String(36),nullable=False),sa.Column('approver_role',sa.String(40),nullable=False),sa.Column('status',sa.String(30),nullable=False,server_default='pending',index=True),sa.Column('comment',sa.Text()),sa.Column('requested_at',sa.DateTime(timezone=True),nullable=False),sa.Column('decided_at',sa.DateTime(timezone=True)))
    op.create_table('report_schedules',sa.Column('id',sa.String(36),primary_key=True),sa.Column('name',sa.String(160),nullable=False),sa.Column('frequency',sa.String(30),nullable=False,server_default='weekly'),sa.Column('recipients',sa.JSON(),nullable=False),sa.Column('report_type',sa.String(40),nullable=False,server_default='status'),sa.Column('active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('last_run',sa.DateTime(timezone=True)),sa.Column('created_by',sa.String(36),nullable=False))
    op.create_table('report_runs',sa.Column('id',sa.String(36),primary_key=True),sa.Column('schedule_id',sa.String(36),index=True),sa.Column('report_type',sa.String(40),nullable=False),sa.Column('format',sa.String(20),nullable=False),sa.Column('status',sa.String(30),nullable=False,server_default='completed'),sa.Column('filename',sa.String(255),nullable=False),sa.Column('created_by',sa.String(36),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('notifications',sa.Column('id',sa.String(36),primary_key=True),sa.Column('user_id',sa.String(36),nullable=False,index=True),sa.Column('title',sa.String(180),nullable=False),sa.Column('message',sa.Text(),nullable=False),sa.Column('type',sa.String(40),nullable=False,server_default='info'),sa.Column('read',sa.Boolean(),nullable=False,server_default=sa.false(),index=True),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,index=True))

def downgrade():
    for t in ['notifications','report_runs','report_schedules','approvals','audit_logs','records','users']:op.drop_table(t)
