export const seedData = {
  "Annual & Monthly Plan": [
    {
      "Year": 2026,
      "Quarter": "Q1",
      "Month": "Sep-26",
      "WBS": "1",
      "Activity / Deliverable": "Project initiation & governance",
      "Planned Output": "Approved governance framework",
      "Planned Start": "2026-09-01",
      "Planned Finish": "2026-10-15",
      "Budget": 300000,
      "Responsible": "Project Manager"
    },
    {
      "Year": 2026,
      "Quarter": "Q1",
      "Month": "Oct-26",
      "WBS": "2",
      "Activity / Deliverable": "Digital service assessment",
      "Planned Output": "Assessment report & prioritized services",
      "Planned Start": "2026-09-15",
      "Planned Finish": "2026-12-15",
      "Budget": 250000,
      "Responsible": "Business Analyst"
    },
    {
      "Year": 2026,
      "Quarter": "Q2",
      "Month": "Nov-26",
      "WBS": "2",
      "Activity / Deliverable": "Requirements & service prioritization",
      "Planned Output": "Requirements baseline",
      "Planned Start": "2026-11-01",
      "Planned Finish": "2027-01-15",
      "Budget": 200000,
      "Responsible": "Business Analyst"
    },
    {
      "Year": 2027,
      "Quarter": "Q2",
      "Month": "Jan-27",
      "WBS": "3",
      "Activity / Deliverable": "Architecture & solution design",
      "Planned Output": "Approved architecture",
      "Planned Start": "2027-01-01",
      "Planned Finish": "2027-03-31",
      "Budget": 300000,
      "Responsible": "Technical Lead"
    },
    {
      "Year": 2027,
      "Quarter": "Q2",
      "Month": "Feb-27",
      "WBS": "6",
      "Activity / Deliverable": "Cloud/DevOps/security enablement",
      "Planned Output": "Core infrastructure foundation",
      "Planned Start": "2027-02-01",
      "Planned Finish": "2027-06-30",
      "Budget": 200000,
      "Responsible": "Infrastructure Lead"
    },
    {
      "Year": 2027,
      "Quarter": "Q3",
      "Month": "Apr-27",
      "WBS": "7",
      "Activity / Deliverable": "Capacity building phase 1",
      "Planned Output": "Training program launched",
      "Planned Start": "2027-04-01",
      "Planned Finish": "2027-09-30",
      "Budget": 120000,
      "Responsible": "Capacity Building Lead"
    },
    {
      "Year": 2027,
      "Quarter": "Q4",
      "Month": "Jul-27",
      "WBS": "4",
      "Activity / Deliverable": "Incubation center setup",
      "Planned Output": "Center operational readiness",
      "Planned Start": "2027-01-01",
      "Planned Finish": "2027-12-31",
      "Budget": 850000,
      "Responsible": "Incubation Center Lead"
    },
    {
      "Year": 2027,
      "Quarter": "Q4",
      "Month": "Oct-27",
      "WBS": "5",
      "Activity / Deliverable": "Startup incubation preparation",
      "Planned Output": "Startup selection framework",
      "Planned Start": "2027-07-01",
      "Planned Finish": "2027-12-31",
      "Budget": 180000,
      "Responsible": "Startup Program Lead"
    },
    {
      "Year": 2028,
      "Quarter": "Q1",
      "Month": "Jan-28",
      "WBS": "3",
      "Activity / Deliverable": "Digital service development",
      "Planned Output": "Release wave 1",
      "Planned Start": "2028-01-01",
      "Planned Finish": "2028-06-30",
      "Budget": 450000,
      "Responsible": "Software Engineering Lead"
    },
    {
      "Year": 2028,
      "Quarter": "Q2",
      "Month": "Apr-28",
      "WBS": "8",
      "Activity / Deliverable": "Testing & deployment",
      "Planned Output": "UAT and production deployment wave 1",
      "Planned Start": "2028-04-01",
      "Planned Finish": "2028-09-30",
      "Budget": 220000,
      "Responsible": "Technical Lead"
    },
    {
      "Year": 2028,
      "Quarter": "Q3",
      "Month": "Jul-28",
      "WBS": "5",
      "Activity / Deliverable": "Startup incubation cycle 1",
      "Planned Output": "Supported startup cohort",
      "Planned Start": "2028-07-01",
      "Planned Finish": "2028-12-31",
      "Budget": 220000,
      "Responsible": "Startup Program Lead"
    },
    {
      "Year": 2028,
      "Quarter": "Q4",
      "Month": "Oct-28",
      "WBS": "7",
      "Activity / Deliverable": "Capacity building phase 2",
      "Planned Output": "Advanced training delivered",
      "Planned Start": "2028-10-01",
      "Planned Finish": "2029-03-31",
      "Budget": 140000,
      "Responsible": "Capacity Building Lead"
    },
    {
      "Year": 2029,
      "Quarter": "Q1",
      "Month": "Jan-29",
      "WBS": "8",
      "Activity / Deliverable": "Operationalization",
      "Planned Output": "Service adoption and transition",
      "Planned Start": "2029-01-01",
      "Planned Finish": "2029-03-31",
      "Budget": 230000,
      "Responsible": "Technical Lead"
    },
    {
      "Year": 2029,
      "Quarter": "Q2",
      "Month": "Apr-29",
      "WBS": "5",
      "Activity / Deliverable": "Startup incubation cycle 2",
      "Planned Output": "Enterprise support outcomes",
      "Planned Start": "2029-01-01",
      "Planned Finish": "2029-06-30",
      "Budget": 250000,
      "Responsible": "Startup Program Lead"
    },
    {
      "Year": 2029,
      "Quarter": "Q3",
      "Month": "Jul-29",
      "WBS": "10",
      "Activity / Deliverable": "Closure & sustainability",
      "Planned Output": "Handover and sustainability plan",
      "Planned Start": "2029-07-01",
      "Planned Finish": "2029-08-31",
      "Budget": 150000,
      "Responsible": "Project Manager"
    }
  ],
  "AI & Software Workstream": [
    {
      "ID": "SW-01",
      "Workstream": "Architecture",
      "Activity": "Cloud-native reference architecture",
      "Technology / Method": "Docker/Kubernetes/API Gateway",
      "Deliverable": "Architecture blueprint",
      "Owner": "Technical Lead",
      "Start": "2027-01-01",
      "Finish": "2027-03-31",
      "Progress": 0.15,
      "Status": "In Progress",
      "KPI": "Architecture approved"
    },
    {
      "ID": "SW-02",
      "Workstream": "Software Engineering",
      "Activity": "Digital service APIs",
      "Technology / Method": "Python/FastAPI/REST",
      "Deliverable": "Production-ready APIs",
      "Owner": "Software Lead",
      "Start": "2027-03-01",
      "Finish": "2028-03-31",
      "Progress": 0.1,
      "Status": "In Progress",
      "KPI": "Services released"
    },
    {
      "ID": "SW-03",
      "Workstream": "DevOps",
      "Activity": "CI/CD automation",
      "Technology / Method": "Git/GitHub Actions/Jenkins",
      "Deliverable": "Automated deployment pipelines",
      "Owner": "DevOps Engineer",
      "Start": "2027-02-01",
      "Finish": "2028-06-30",
      "Progress": 0.1,
      "Status": "In Progress",
      "KPI": "Deployment automation"
    },
    {
      "ID": "SW-04",
      "Workstream": "Observability",
      "Activity": "Monitoring and logging",
      "Technology / Method": "Prometheus/Grafana/Zabbix",
      "Deliverable": "Operational dashboards and alerts",
      "Owner": "DevOps Engineer",
      "Start": "2027-04-01",
      "Finish": "2028-09-30",
      "Progress": 0,
      "Status": "Not Started",
      "KPI": "Availability"
    },
    {
      "ID": "SW-05",
      "Workstream": "Cybersecurity",
      "Activity": "Identity and access controls",
      "Technology / Method": "RBAC/MFA/Audit logging",
      "Deliverable": "Security controls",
      "Owner": "Security Lead",
      "Start": "2027-03-01",
      "Finish": "2028-06-30",
      "Progress": 0.05,
      "Status": "In Progress",
      "KPI": "Critical controls implemented"
    },
    {
      "ID": "SW-06",
      "Workstream": "AI",
      "Activity": "AI use-case discovery",
      "Technology / Method": "Python/ML/NLP",
      "Deliverable": "AI use-case portfolio",
      "Owner": "AI Expert",
      "Start": "2027-04-01",
      "Finish": "2028-03-31",
      "Progress": 0,
      "Status": "Not Started",
      "KPI": "AI prototypes"
    },
    {
      "ID": "SW-07",
      "Workstream": "AI",
      "Activity": "Prototype priority AI applications",
      "Technology / Method": "Python/TensorFlow/PyTorch",
      "Deliverable": "Validated prototypes",
      "Owner": "AI Expert",
      "Start": "2028-01-01",
      "Finish": "2029-03-31",
      "Progress": 0,
      "Status": "Not Started",
      "KPI": "Prototypes validated"
    },
    {
      "ID": "SW-08",
      "Workstream": "Data",
      "Activity": "Data governance & analytics",
      "Technology / Method": "PostgreSQL/APIs/BI",
      "Deliverable": "Data governance and analytics layer",
      "Owner": "Data Specialist",
      "Start": "2027-07-01",
      "Finish": "2029-06-30",
      "Progress": 0,
      "Status": "Not Started",
      "KPI": "Data quality"
    }
  ],
  "WBS": [
    {
      "WBS ID": "1",
      "Parent WBS": null,
      "WBS Level": 1,
      "Project Phase": "Initiation",
      "Work Package": "Project Initiation & Governance",
      "Deliverable": "Approved Governance Framework",
      "Description": "Project charter, governance, steering and reporting arrangements",
      "Responsible Person": "Project Manager",
      "Start Date": "2026-09-01",
      "Finish Date": "2026-10-15",
      "Budget": 300000,
      "Status": "Completed",
      "% Complete": 0.8,
      "Milestone?": "Yes",
      "Notes": null
    },
    {
      "WBS ID": "2",
      "Parent WBS": null,
      "WBS Level": 1,
      "Project Phase": "Planning",
      "Work Package": "Digital Service Assessment & Requirements",
      "Deliverable": "Digital Service Assessment",
      "Description": "Assessment, business processes, requirements and service prioritization",
      "Responsible Person": "Business Analyst",
      "Start Date": "2026-09-15",
      "Finish Date": "2027-01-15",
      "Budget": 450000,
      "Status": "In Progress",
      "% Complete": 0.6,
      "Milestone?": "Yes",
      "Notes": null
    },
    {
      "WBS ID": "3",
      "Parent WBS": null,
      "WBS Level": 1,
      "Project Phase": "Development",
      "Work Package": "Electronic Service Delivery Development",
      "Deliverable": "Priority Digital Services",
      "Description": "Design, development, integration and testing of priority services",
      "Responsible Person": "Software Engineering Lead",
      "Start Date": "2027-01-01",
      "Finish Date": "2028-03-31",
      "Budget": 1300000,
      "Status": "In Progress",
      "% Complete": 0.2,
      "Milestone?": "No",
      "Notes": null
    },
    {
      "WBS ID": "4",
      "Parent WBS": null,
      "WBS Level": 1,
      "Project Phase": "Incubation",
      "Work Package": "High-Technology Innovation Incubation Center",
      "Deliverable": "Incubation Center Operational",
      "Description": "Center setup, facilities, governance, technology and operations",
      "Responsible Person": "Incubation Center Lead",
      "Start Date": "2027-01-01",
      "Finish Date": "2027-12-31",
      "Budget": 850000,
      "Status": "In Progress",
      "% Complete": 0.15,
      "Milestone?": "Yes",
      "Notes": null
    },
    {
      "WBS ID": "5",
      "Parent WBS": null,
      "WBS Level": 1,
      "Project Phase": "Enterprise Support",
      "Work Package": "Startup Incubation & Enterprise Support",
      "Deliverable": "Supported Innovation Enterprises",
      "Description": "Startup selection, incubation, mentoring, acceleration and enterprise support",
      "Responsible Person": "Startup Program Lead",
      "Start Date": "2027-07-01",
      "Finish Date": "2029-03-31",
      "Budget": 650000,
      "Status": "Not Started",
      "% Complete": 0,
      "Milestone?": "No",
      "Notes": null
    },
    {
      "WBS ID": "6",
      "Parent WBS": null,
      "WBS Level": 1,
      "Project Phase": "Technology",
      "Work Package": "Digital Infrastructure & Technology Enablement",
      "Deliverable": "Technology Platform",
      "Description": "Cloud, DevOps, cybersecurity, identity, data and collaboration infrastructure",
      "Responsible Person": "Infrastructure Lead",
      "Start Date": "2027-01-01",
      "Finish Date": "2028-06-30",
      "Budget": 500000,
      "Status": "In Progress",
      "% Complete": 0.1,
      "Milestone?": "No",
      "Notes": null
    },
    {
      "WBS ID": "7",
      "Parent WBS": null,
      "WBS Level": 1,
      "Project Phase": "Capacity Building",
      "Work Package": "Capacity Building & Knowledge Transfer",
      "Deliverable": "Training & Skills Program",
      "Description": "Technical, digital-service and entrepreneurship capacity development",
      "Responsible Person": "Capacity Building Lead",
      "Start Date": "2027-04-01",
      "Finish Date": "2029-06-30",
      "Budget": 400000,
      "Status": "Not Started",
      "% Complete": 0,
      "Milestone?": "No",
      "Notes": null
    },
    {
      "WBS ID": "8",
      "Parent WBS": null,
      "WBS Level": 1,
      "Project Phase": "Deployment",
      "Work Package": "Testing, Deployment & Operationalization",
      "Deliverable": "Operational Digital Services",
      "Description": "UAT, deployment, adoption, support and transition to operations",
      "Responsible Person": "Technical Lead",
      "Start Date": "2028-01-01",
      "Finish Date": "2029-03-31",
      "Budget": 450000,
      "Status": "Not Started",
      "% Complete": 0,
      "Milestone?": "Yes",
      "Notes": null
    },
    {
      "WBS ID": "9",
      "Parent WBS": null,
      "WBS Level": 1,
      "Project Phase": "M&E",
      "Work Package": "Monitoring, Evaluation & Performance Management",
      "Deliverable": "Performance Framework",
      "Description": "KPIs, EVM, outcome monitoring, reporting and lessons learned",
      "Responsible Person": "M&E / PMO Lead",
      "Start Date": "2026-09-01",
      "Finish Date": "2029-08-15",
      "Budget": 250000,
      "Status": "In Progress",
      "% Complete": 0.1,
      "Milestone?": "No",
      "Notes": null
    },
    {
      "WBS ID": "10",
      "Parent WBS": null,
      "WBS Level": 1,
      "Project Phase": "Closure",
      "Work Package": "Project Closure & Sustainability",
      "Deliverable": "Closure & Sustainability Plan",
      "Description": "Handover, sustainability, institutionalization and final reporting",
      "Responsible Person": "Project Manager",
      "Start Date": "2029-07-01",
      "Finish Date": "2029-08-31",
      "Budget": 150000,
      "Status": "Not Started",
      "% Complete": 0,
      "Milestone?": "Yes",
      "Notes": null
    }
  ],
  "Task Register": [
    {
      "Task ID": "T001",
      "WBS ID": "1",
      "Task Name": "Project Charter & Governance",
      "Description": "Finalize charter, governance and reporting framework",
      "Project Phase": "Initiation",
      "Responsible Person": "Project Manager",
      "Department": "PMO",
      "Priority": "High",
      "Predecessor": null,
      "Dependency Type": null,
      "Planned Start": "2026-09-01",
      "Planned Finish": "2026-10-15",
      "Duration": "=L4-K4+1",
      "Actual Start": "2026-10-15",
      "Actual Finish": 0.8,
      "% Complete": "In Progress",
      "Status": 300000,
      "Planned Cost": 295000,
      "Actual Cost": null,
      "Cost Variance": "=R4-S4",
      "Days Remaining": "=IF(Q4=\"Completed\",0,L4-TODAY())",
      "Delayed?": "=IF(AND(Q4<>\"Completed\",TODAY()>L4),\"YES\",\"NO\")",
      "Milestone?": "=IFERROR(XLOOKUP(B4,WBS!A:A,WBS!N:N,\"No\"),\"No\")",
      "Notes": null
    },
    {
      "Task ID": "T002",
      "WBS ID": "2",
      "Task Name": "Digital Service Assessment",
      "Description": "Assess priority services and current-state processes",
      "Project Phase": "Planning",
      "Responsible Person": "Business Analyst",
      "Department": "PMO",
      "Priority": "High",
      "Predecessor": "T001",
      "Dependency Type": "FS",
      "Planned Start": "2026-09-15",
      "Planned Finish": "2026-12-15",
      "Duration": "=L5-K5+1",
      "Actual Start": null,
      "Actual Finish": 0.6,
      "% Complete": "In Progress",
      "Status": 250000,
      "Planned Cost": 155000,
      "Actual Cost": null,
      "Cost Variance": "=R5-S5",
      "Days Remaining": "=IF(Q5=\"Completed\",0,L5-TODAY())",
      "Delayed?": "=IF(AND(Q5<>\"Completed\",TODAY()>L5),\"YES\",\"NO\")",
      "Milestone?": "=IFERROR(XLOOKUP(B5,WBS!A:A,WBS!N:N,\"No\"),\"No\")",
      "Notes": null
    },
    {
      "Task ID": "T003",
      "WBS ID": "2",
      "Task Name": "Requirements & Service Prioritization",
      "Description": "Define functional and non-functional requirements",
      "Project Phase": "Planning",
      "Responsible Person": "Business Analyst",
      "Department": "PMO",
      "Priority": "High",
      "Predecessor": "T002",
      "Dependency Type": "FS",
      "Planned Start": "2026-11-01",
      "Planned Finish": "2027-01-15",
      "Duration": "=L6-K6+1",
      "Actual Start": null,
      "Actual Finish": 0.45,
      "% Complete": "In Progress",
      "Status": 200000,
      "Planned Cost": 65000,
      "Actual Cost": null,
      "Cost Variance": "=R6-S6",
      "Days Remaining": "=IF(Q6=\"Completed\",0,L6-TODAY())",
      "Delayed?": "=IF(AND(Q6<>\"Completed\",TODAY()>L6),\"YES\",\"NO\")",
      "Milestone?": "=IFERROR(XLOOKUP(B6,WBS!A:A,WBS!N:N,\"No\"),\"No\")",
      "Notes": null
    },
    {
      "Task ID": "T004",
      "WBS ID": "3",
      "Task Name": "Architecture & Solution Design",
      "Description": "Define scalable architecture for digital services",
      "Project Phase": "Development",
      "Responsible Person": "Technical Lead",
      "Department": "Software Engineering",
      "Priority": "Critical",
      "Predecessor": "T003",
      "Dependency Type": "FS",
      "Planned Start": "2027-01-01",
      "Planned Finish": "2027-03-31",
      "Duration": "=L7-K7+1",
      "Actual Start": null,
      "Actual Finish": 0.15,
      "% Complete": "In Progress",
      "Status": 300000,
      "Planned Cost": 55000,
      "Actual Cost": null,
      "Cost Variance": "=R7-S7",
      "Days Remaining": "=IF(Q7=\"Completed\",0,L7-TODAY())",
      "Delayed?": "=IF(AND(Q7<>\"Completed\",TODAY()>L7),\"YES\",\"NO\")",
      "Milestone?": "=IFERROR(XLOOKUP(B7,WBS!A:A,WBS!N:N,\"No\"),\"No\")",
      "Notes": null
    },
    {
      "Task ID": "T005",
      "WBS ID": "3",
      "Task Name": "Digital Service Development",
      "Description": "Develop and integrate priority electronic services",
      "Project Phase": "Development",
      "Responsible Person": "Software Engineering Lead",
      "Department": "Software Engineering",
      "Priority": "Critical",
      "Predecessor": "T004",
      "Dependency Type": "FS",
      "Planned Start": "2027-03-01",
      "Planned Finish": "2028-03-31",
      "Duration": "=L8-K8+1",
      "Actual Start": null,
      "Actual Finish": 0.1,
      "% Complete": "In Progress",
      "Status": 1000000,
      "Planned Cost": 80000,
      "Actual Cost": null,
      "Cost Variance": "=R8-S8",
      "Days Remaining": "=IF(Q8=\"Completed\",0,L8-TODAY())",
      "Delayed?": "=IF(AND(Q8<>\"Completed\",TODAY()>L8),\"YES\",\"NO\")",
      "Milestone?": "=IFERROR(XLOOKUP(B8,WBS!A:A,WBS!N:N,\"No\"),\"No\")",
      "Notes": null
    },
    {
      "Task ID": "T006",
      "WBS ID": "4",
      "Task Name": "Incubation Center Setup",
      "Description": "Establish physical/operational incubation center",
      "Project Phase": "Incubation",
      "Responsible Person": "Incubation Center Lead",
      "Department": "Operations",
      "Priority": "High",
      "Predecessor": "T003",
      "Dependency Type": "FS",
      "Planned Start": "2027-01-01",
      "Planned Finish": "2027-12-31",
      "Duration": "=L9-K9+1",
      "Actual Start": null,
      "Actual Finish": 0.15,
      "% Complete": "In Progress",
      "Status": 850000,
      "Planned Cost": 110000,
      "Actual Cost": null,
      "Cost Variance": "=R9-S9",
      "Days Remaining": "=IF(Q9=\"Completed\",0,L9-TODAY())",
      "Delayed?": "=IF(AND(Q9<>\"Completed\",TODAY()>L9),\"YES\",\"NO\")",
      "Milestone?": "=IFERROR(XLOOKUP(B9,WBS!A:A,WBS!N:N,\"No\"),\"No\")",
      "Notes": null
    },
    {
      "Task ID": "T007",
      "WBS ID": "5",
      "Task Name": "Startup Selection & Incubation",
      "Description": "Select and support innovation enterprises",
      "Project Phase": "Enterprise Support",
      "Responsible Person": "Startup Program Lead",
      "Department": "Operations",
      "Priority": "High",
      "Predecessor": "T006",
      "Dependency Type": "FS",
      "Planned Start": "2027-07-01",
      "Planned Finish": "2029-03-31",
      "Duration": "=L10-K10+1",
      "Actual Start": null,
      "Actual Finish": 0.0,
      "% Complete": "Not Started",
      "Status": 650000,
      "Planned Cost": 0,
      "Actual Cost": null,
      "Cost Variance": "=R10-S10",
      "Days Remaining": "=IF(Q10=\"Completed\",0,L10-TODAY())",
      "Delayed?": "=IF(AND(Q10<>\"Completed\",TODAY()>L10),\"YES\",\"NO\")",
      "Milestone?": "=IFERROR(XLOOKUP(B10,WBS!A:A,WBS!N:N,\"No\"),\"No\")",
      "Notes": null
    },
    {
      "Task ID": "T008",
      "WBS ID": "6",
      "Task Name": "Cloud/DevOps & Security Enablement",
      "Description": "Establish infrastructure, CI/CD, monitoring and security controls",
      "Project Phase": "Technology",
      "Responsible Person": "Infrastructure Lead",
      "Department": "Infrastructure",
      "Priority": "High",
      "Predecessor": "T004",
      "Dependency Type": "FS",
      "Planned Start": "2027-02-01",
      "Planned Finish": "2028-06-30",
      "Duration": "=L11-K11+1",
      "Actual Start": null,
      "Actual Finish": 0.1,
      "% Complete": "In Progress",
      "Status": 500000,
      "Planned Cost": 45000,
      "Actual Cost": null,
      "Cost Variance": "=R11-S11",
      "Days Remaining": "=IF(Q11=\"Completed\",0,L11-TODAY())",
      "Delayed?": "=IF(AND(Q11<>\"Completed\",TODAY()>L11),\"YES\",\"NO\")",
      "Milestone?": "=IFERROR(XLOOKUP(B11,WBS!A:A,WBS!N:N,\"No\"),\"No\")",
      "Notes": null
    },
    {
      "Task ID": "T009",
      "WBS ID": "7",
      "Task Name": "Capacity Building",
      "Description": "Deliver technical, digital-service and entrepreneurship training",
      "Project Phase": "Capacity Building",
      "Responsible Person": "Capacity Building Lead",
      "Department": "HR",
      "Priority": "Medium",
      "Predecessor": "T006",
      "Dependency Type": "FS",
      "Planned Start": "2027-04-01",
      "Planned Finish": "2029-06-30",
      "Duration": "=L12-K12+1",
      "Actual Start": null,
      "Actual Finish": 0.0,
      "% Complete": "Not Started",
      "Status": 400000,
      "Planned Cost": 0,
      "Actual Cost": null,
      "Cost Variance": "=R12-S12",
      "Days Remaining": "=IF(Q12=\"Completed\",0,L12-TODAY())",
      "Delayed?": "=IF(AND(Q12<>\"Completed\",TODAY()>L12),\"YES\",\"NO\")",
      "Milestone?": "=IFERROR(XLOOKUP(B12,WBS!A:A,WBS!N:N,\"No\"),\"No\")",
      "Notes": null
    },
    {
      "Task ID": "T010",
      "WBS ID": "8",
      "Task Name": "Testing & Deployment",
      "Description": "UAT, deployment, adoption and operational transition",
      "Project Phase": "Deployment",
      "Responsible Person": "Technical Lead",
      "Department": "Software Engineering",
      "Priority": "High",
      "Predecessor": "T005",
      "Dependency Type": "FS",
      "Planned Start": "2028-01-01",
      "Planned Finish": "2029-03-31",
      "Duration": "=L13-K13+1",
      "Actual Start": null,
      "Actual Finish": 0.0,
      "% Complete": "Not Started",
      "Status": 450000,
      "Planned Cost": 0,
      "Actual Cost": null,
      "Cost Variance": "=R13-S13",
      "Days Remaining": "=IF(Q13=\"Completed\",0,L13-TODAY())",
      "Delayed?": "=IF(AND(Q13<>\"Completed\",TODAY()>L13),\"YES\",\"NO\")",
      "Milestone?": "=IFERROR(XLOOKUP(B13,WBS!A:A,WBS!N:N,\"No\"),\"No\")",
      "Notes": null
    },
    {
      "Task ID": "T011",
      "WBS ID": "9",
      "Task Name": "Monitoring & Evaluation",
      "Description": "Track KPIs, outcomes, risks, EVM and reports",
      "Project Phase": "M&E",
      "Responsible Person": "M&E / PMO Lead",
      "Department": "PMO",
      "Priority": "High",
      "Predecessor": "T001",
      "Dependency Type": "FS",
      "Planned Start": "2026-09-01",
      "Planned Finish": "2029-08-15",
      "Duration": "=L14-K14+1",
      "Actual Start": null,
      "Actual Finish": 0.1,
      "% Complete": "In Progress",
      "Status": 250000,
      "Planned Cost": 30000,
      "Actual Cost": null,
      "Cost Variance": "=R14-S14",
      "Days Remaining": "=IF(Q14=\"Completed\",0,L14-TODAY())",
      "Delayed?": "=IF(AND(Q14<>\"Completed\",TODAY()>L14),\"YES\",\"NO\")",
      "Milestone?": "=IFERROR(XLOOKUP(B14,WBS!A:A,WBS!N:N,\"No\"),\"No\")",
      "Notes": null
    },
    {
      "Task ID": "T012",
      "WBS ID": "10",
      "Task Name": "Closure & Sustainability",
      "Description": "Handover, sustainability and final reporting",
      "Project Phase": "Closure",
      "Responsible Person": "Project Manager",
      "Department": "PMO",
      "Priority": "Medium",
      "Predecessor": "T010",
      "Dependency Type": "FS",
      "Planned Start": "2029-07-01",
      "Planned Finish": "2029-08-31",
      "Duration": "=L15-K15+1",
      "Actual Start": null,
      "Actual Finish": 0.0,
      "% Complete": "Not Started",
      "Status": 150000,
      "Planned Cost": 0,
      "Actual Cost": null,
      "Cost Variance": "=R15-S15",
      "Days Remaining": "=IF(Q15=\"Completed\",0,L15-TODAY())",
      "Delayed?": "=IF(AND(Q15<>\"Completed\",TODAY()>L15),\"YES\",\"NO\")",
      "Milestone?": "=IFERROR(XLOOKUP(B15,WBS!A:A,WBS!N:N,\"No\"),\"No\")",
      "Notes": null
    }
  ],
  "Resource Plan": [
    {
      "Resource ID": "R001",
      "Resource Name": "Project Manager",
      "Role": "Project Manager",
      "Department": "PMO",
      "Resource Type": "Staff",
      "Task/WBS": "1/9",
      "Planned Allocation": 80,
      "Actual Allocation": 75,
      "Unit": "%",
      "Start Date": "2026-09-01",
      "End Date": "2029-08-31",
      "Utilization %": 0.75,
      "Cost Rate": 1800,
      "Planned Resource Cost": "=G4/100*(K4-J4+1)*M4",
      "Actual Resource Cost": "=H4/100*(K4-J4+1)*M4"
    },
    {
      "Resource ID": "R002",
      "Resource Name": "Software Engineering Team",
      "Role": "Software Engineers",
      "Department": "Software Engineering",
      "Resource Type": "Staff",
      "Task/WBS": "3/8",
      "Planned Allocation": 100,
      "Actual Allocation": 60,
      "Unit": "%",
      "Start Date": "2027-01-01",
      "End Date": "2029-03-31",
      "Utilization %": 0.6,
      "Cost Rate": 3200,
      "Planned Resource Cost": "=G5/100*(K5-J5+1)*M5",
      "Actual Resource Cost": "=H5/100*(K5-J5+1)*M5"
    },
    {
      "Resource ID": "R003",
      "Resource Name": "AI & Data Specialist",
      "Role": "AI/ML & Data",
      "Department": "Software Engineering",
      "Resource Type": "Staff",
      "Task/WBS": "3/9",
      "Planned Allocation": 60,
      "Actual Allocation": 30,
      "Unit": "%",
      "Start Date": "2027-01-01",
      "End Date": "2029-06-30",
      "Utilization %": 0.3,
      "Cost Rate": 3000,
      "Planned Resource Cost": "=G6/100*(K6-J6+1)*M6",
      "Actual Resource Cost": "=H6/100*(K6-J6+1)*M6"
    },
    {
      "Resource ID": "R004",
      "Resource Name": "DevOps / Cloud Engineer",
      "Role": "Cloud & DevOps",
      "Department": "Infrastructure",
      "Resource Type": "Staff",
      "Task/WBS": "6/8",
      "Planned Allocation": 80,
      "Actual Allocation": 35,
      "Unit": "%",
      "Start Date": "2027-01-01",
      "End Date": "2029-03-31",
      "Utilization %": 0.35,
      "Cost Rate": 3000,
      "Planned Resource Cost": "=G7/100*(K7-J7+1)*M7",
      "Actual Resource Cost": "=H7/100*(K7-J7+1)*M7"
    },
    {
      "Resource ID": "R005",
      "Resource Name": "Incubation Manager",
      "Role": "Incubation Manager",
      "Department": "Operations",
      "Resource Type": "Staff",
      "Task/WBS": "4/5",
      "Planned Allocation": 100,
      "Actual Allocation": 20,
      "Unit": "%",
      "Start Date": "2027-01-01",
      "End Date": "2029-06-30",
      "Utilization %": 0.2,
      "Cost Rate": 2200,
      "Planned Resource Cost": "=G8/100*(K8-J8+1)*M8",
      "Actual Resource Cost": "=H8/100*(K8-J8+1)*M8"
    },
    {
      "Resource ID": "R006",
      "Resource Name": "M&E Specialist",
      "Role": "M&E Specialist",
      "Department": "PMO",
      "Resource Type": "Staff",
      "Task/WBS": "9",
      "Planned Allocation": 60,
      "Actual Allocation": 20,
      "Unit": "%",
      "Start Date": "2026-09-01",
      "End Date": "2029-08-15",
      "Utilization %": 0.2,
      "Cost Rate": 2400,
      "Planned Resource Cost": "=G9/100*(K9-J9+1)*M9",
      "Actual Resource Cost": "=H9/100*(K9-J9+1)*M9"
    }
  ],
  "Baseline Budget": [
    {
      "Budget ID": "B001",
      "WBS": "1",
      "Cost Category": "Personnel",
      "Cost Item": "Project Management",
      "Description": "PMO management",
      "Quantity": 1,
      "Unit": "LS",
      "Unit Rate": 300000,
      "Planned Cost": "=F4*H4",
      "Budget Period": "Sep-26",
      "Funding Source": "Government",
      "Approved Budget": 300000,
      "Contingency": 0,
      "Total Budget": "=L4+M4"
    },
    {
      "Budget ID": "B002",
      "WBS": "1.1",
      "Cost Category": "Consulting",
      "Cost Item": "Requirements",
      "Description": "Analysis and workshops",
      "Quantity": 1,
      "Unit": "LS",
      "Unit Rate": 450000,
      "Planned Cost": "=F5*H5",
      "Budget Period": "Sep-26",
      "Funding Source": "Government",
      "Approved Budget": 450000,
      "Contingency": 25000,
      "Total Budget": "=L5+M5"
    },
    {
      "Budget ID": "B003",
      "WBS": "2",
      "Cost Category": "Design",
      "Cost Item": "Architecture",
      "Description": "Solution architecture",
      "Quantity": 1,
      "Unit": "LS",
      "Unit Rate": 700000,
      "Planned Cost": "=F6*H6",
      "Budget Period": "Oct-26",
      "Funding Source": "Government",
      "Approved Budget": 700000,
      "Contingency": 50000,
      "Total Budget": "=L6+M6"
    },
    {
      "Budget ID": "B004",
      "WBS": "3",
      "Cost Category": "Development",
      "Cost Item": "Software",
      "Description": "Platform development",
      "Quantity": 1,
      "Unit": "LS",
      "Unit Rate": 2200000,
      "Planned Cost": "=F7*H7",
      "Budget Period": "Jan-27",
      "Funding Source": "Government",
      "Approved Budget": 2200000,
      "Contingency": 150000,
      "Total Budget": "=L7+M7"
    },
    {
      "Budget ID": "B005",
      "WBS": "4",
      "Cost Category": "Implementation",
      "Cost Item": "Deployment",
      "Description": "Deployment and training",
      "Quantity": 1,
      "Unit": "LS",
      "Unit Rate": 900000,
      "Planned Cost": "=F8*H8",
      "Budget Period": "Feb-27",
      "Funding Source": "Government",
      "Approved Budget": 900000,
      "Contingency": 50000,
      "Total Budget": "=L8+M8"
    },
    {
      "Budget ID": "B006",
      "WBS": "5",
      "Cost Category": "Closure",
      "Cost Item": "Closure",
      "Description": "Handover",
      "Quantity": 1,
      "Unit": "LS",
      "Unit Rate": 450000,
      "Planned Cost": "=F9*H9",
      "Budget Period": "Feb-27",
      "Funding Source": "Government",
      "Approved Budget": 450000,
      "Contingency": 25000,
      "Total Budget": "=L9+M9"
    }
  ],
  "Actual Cost": [
    {
      "Transaction ID": "AC001",
      "Date": "2026-09-08",
      "WBS": "1",
      "Task ID": "T001",
      "Cost Category": "Personnel",
      "Cost Item": "Project Management",
      "Supplier/Payee": "Internal",
      "Description": "Charter work",
      "Invoice/Reference": "REF-001",
      "Quantity": 1,
      "Unit Cost": 295000,
      "Actual Cost": 295000,
      "Payment Status": "Paid",
      "Payment Date": "2026-09-15",
      "Responsible Person": "Project Manager",
      "Notes": null
    },
    {
      "Transaction ID": "AC002",
      "Date": "2026-09-20",
      "WBS": "1.1",
      "Task ID": "T002",
      "Cost Category": "Consulting",
      "Cost Item": "Requirements",
      "Supplier/Payee": "Consultant",
      "Description": "Workshops",
      "Invoice/Reference": "REF-002",
      "Quantity": 1,
      "Unit Cost": 290000,
      "Actual Cost": 290000,
      "Payment Status": "Paid",
      "Payment Date": "2026-09-28",
      "Responsible Person": "Business Analyst",
      "Notes": null
    },
    {
      "Transaction ID": "AC003",
      "Date": "2026-10-15",
      "WBS": "2",
      "Task ID": "T003",
      "Cost Category": "Design",
      "Cost Item": "Architecture",
      "Supplier/Payee": "Consultant",
      "Description": "Architecture work",
      "Invoice/Reference": "REF-003",
      "Quantity": 1,
      "Unit Cost": 410000,
      "Actual Cost": 410000,
      "Payment Status": "Partially Paid",
      "Payment Date": null,
      "Responsible Person": "Technical Lead",
      "Notes": null
    },
    {
      "Transaction ID": "AC004",
      "Date": "2026-11-20",
      "WBS": "3",
      "Task ID": "T004",
      "Cost Category": "Development",
      "Cost Item": "Software",
      "Supplier/Payee": "Vendor",
      "Description": "Development services",
      "Invoice/Reference": "REF-004",
      "Quantity": 1,
      "Unit Cost": 520000,
      "Actual Cost": 520000,
      "Payment Status": "Pending",
      "Payment Date": null,
      "Responsible Person": "Software Lead",
      "Notes": null
    }
  ],
  "Progress Register": [
    {
      "Reporting Date": "2026-11-30",
      "WBS": "='Task Register'!B4",
      "Task ID": "='Task Register'!A4",
      "Task Name": "='Task Register'!C4",
      "Planned %": "=MAX(0,MIN(1,(A4-'Task Register'!K4+1)/('Task Register'!L4-'Task Register'!K4+1)))",
      "Previous Actual %": 0,
      "Current Actual %": "='Task Register'!P4",
      "Cumulative Actual %": "=G4",
      "Progress Variance %": "=H4-E4",
      "Responsible Person": "='Task Register'!F4",
      "Status": "='Task Register'!Q4",
      "Achievement": "Demonstration update",
      "Challenge": "Monitor dependencies",
      "Corrective Action": "Follow up next review"
    },
    {
      "Reporting Date": "2026-11-30",
      "WBS": "='Task Register'!B5",
      "Task ID": "='Task Register'!A5",
      "Task Name": "='Task Register'!C5",
      "Planned %": "=MAX(0,MIN(1,(A5-'Task Register'!K5+1)/('Task Register'!L5-'Task Register'!K5+1)))",
      "Previous Actual %": 0,
      "Current Actual %": "='Task Register'!P5",
      "Cumulative Actual %": "=G5",
      "Progress Variance %": "=H5-E5",
      "Responsible Person": "='Task Register'!F5",
      "Status": "='Task Register'!Q5",
      "Achievement": "Demonstration update",
      "Challenge": "Monitor dependencies",
      "Corrective Action": "Follow up next review"
    },
    {
      "Reporting Date": "2026-11-30",
      "WBS": "='Task Register'!B6",
      "Task ID": "='Task Register'!A6",
      "Task Name": "='Task Register'!C6",
      "Planned %": "=MAX(0,MIN(1,(A6-'Task Register'!K6+1)/('Task Register'!L6-'Task Register'!K6+1)))",
      "Previous Actual %": 0,
      "Current Actual %": "='Task Register'!P6",
      "Cumulative Actual %": "=G6",
      "Progress Variance %": "=H6-E6",
      "Responsible Person": "='Task Register'!F6",
      "Status": "='Task Register'!Q6",
      "Achievement": "Demonstration update",
      "Challenge": "Monitor dependencies",
      "Corrective Action": "Follow up next review"
    },
    {
      "Reporting Date": "2026-11-30",
      "WBS": "='Task Register'!B7",
      "Task ID": "='Task Register'!A7",
      "Task Name": "='Task Register'!C7",
      "Planned %": "=MAX(0,MIN(1,(A7-'Task Register'!K7+1)/('Task Register'!L7-'Task Register'!K7+1)))",
      "Previous Actual %": 0,
      "Current Actual %": "='Task Register'!P7",
      "Cumulative Actual %": "=G7",
      "Progress Variance %": "=H7-E7",
      "Responsible Person": "='Task Register'!F7",
      "Status": "='Task Register'!Q7",
      "Achievement": "Demonstration update",
      "Challenge": "Monitor dependencies",
      "Corrective Action": "Follow up next review"
    },
    {
      "Reporting Date": "2026-11-30",
      "WBS": "='Task Register'!B8",
      "Task ID": "='Task Register'!A8",
      "Task Name": "='Task Register'!C8",
      "Planned %": "=MAX(0,MIN(1,(A8-'Task Register'!K8+1)/('Task Register'!L8-'Task Register'!K8+1)))",
      "Previous Actual %": 0,
      "Current Actual %": "='Task Register'!P8",
      "Cumulative Actual %": "=G8",
      "Progress Variance %": "=H8-E8",
      "Responsible Person": "='Task Register'!F8",
      "Status": "='Task Register'!Q8",
      "Achievement": "Demonstration update",
      "Challenge": "Monitor dependencies",
      "Corrective Action": "Follow up next review"
    },
    {
      "Reporting Date": "2026-11-30",
      "WBS": "='Task Register'!B9",
      "Task ID": "='Task Register'!A9",
      "Task Name": "='Task Register'!C9",
      "Planned %": "=MAX(0,MIN(1,(A9-'Task Register'!K9+1)/('Task Register'!L9-'Task Register'!K9+1)))",
      "Previous Actual %": 0,
      "Current Actual %": "='Task Register'!P9",
      "Cumulative Actual %": "=G9",
      "Progress Variance %": "=H9-E9",
      "Responsible Person": "='Task Register'!F9",
      "Status": "='Task Register'!Q9",
      "Achievement": "Demonstration update",
      "Challenge": "Monitor dependencies",
      "Corrective Action": "Follow up next review"
    },
    {
      "Reporting Date": "2026-11-30",
      "WBS": "='Task Register'!B10",
      "Task ID": "='Task Register'!A10",
      "Task Name": "='Task Register'!C10",
      "Planned %": "=MAX(0,MIN(1,(A10-'Task Register'!K10+1)/('Task Register'!L10-'Task Register'!K10+1)))",
      "Previous Actual %": 0,
      "Current Actual %": "='Task Register'!P10",
      "Cumulative Actual %": "=G10",
      "Progress Variance %": "=H10-E10",
      "Responsible Person": "='Task Register'!F10",
      "Status": "='Task Register'!Q10",
      "Achievement": "Demonstration update",
      "Challenge": "Monitor dependencies",
      "Corrective Action": "Follow up next review"
    }
  ],
  "EVM": [
    {
      "Reporting Period": "2026-09-30",
      "BAC": 5000000,
      "PV": 500000,
      "EV": 400000,
      "AC": 350000,
      "CV": "=D4-E4",
      "SV": "=D4-C4",
      "CPI": "=IFERROR(D4/E4,0)",
      "SPI": "=IFERROR(D4/C4,0)",
      "EAC": "=IFERROR(B4/H4,B4)",
      "ETC": "=J4-E4",
      "VAC": "=B4-J4",
      "TCPI": "=IFERROR((B4-D4)/(B4-E4),0)",
      "Interpretation": "=IF(AND(H4>=1,I4>=1),\"Favorable\",IF(OR(H4<0.85,I4<0.85),\"Critical\",\"Watch\"))"
    },
    {
      "Reporting Period": "2026-10-31",
      "BAC": 5000000,
      "PV": 1250000,
      "EV": 1000000,
      "AC": 850000,
      "CV": "=D5-E5",
      "SV": "=D5-C5",
      "CPI": "=IFERROR(D5/E5,0)",
      "SPI": "=IFERROR(D5/C5,0)",
      "EAC": "=IFERROR(B5/H5,B5)",
      "ETC": "=J5-E5",
      "VAC": "=B5-J5",
      "TCPI": "=IFERROR((B5-D5)/(B5-E5),0)",
      "Interpretation": "=IF(AND(H5>=1,I5>=1),\"Favorable\",IF(OR(H5<0.85,I5<0.85),\"Critical\",\"Watch\"))"
    },
    {
      "Reporting Period": "2026-11-30",
      "BAC": 5000000,
      "PV": 2250000,
      "EV": 1750000,
      "AC": 1515000,
      "CV": "=D6-E6",
      "SV": "=D6-C6",
      "CPI": "=IFERROR(D6/E6,0)",
      "SPI": "=IFERROR(D6/C6,0)",
      "EAC": "=IFERROR(B6/H6,B6)",
      "ETC": "=J6-E6",
      "VAC": "=B6-J6",
      "TCPI": "=IFERROR((B6-D6)/(B6-E6),0)",
      "Interpretation": "=IF(AND(H6>=1,I6>=1),\"Favorable\",IF(OR(H6<0.85,I6<0.85),\"Critical\",\"Watch\"))"
    },
    {
      "Reporting Period": "2026-12-31",
      "BAC": 5000000,
      "PV": 3250000,
      "EV": 2500000,
      "AC": 2300000,
      "CV": "=D7-E7",
      "SV": "=D7-C7",
      "CPI": "=IFERROR(D7/E7,0)",
      "SPI": "=IFERROR(D7/C7,0)",
      "EAC": "=IFERROR(B7/H7,B7)",
      "ETC": "=J7-E7",
      "VAC": "=B7-J7",
      "TCPI": "=IFERROR((B7-D7)/(B7-E7),0)",
      "Interpretation": "=IF(AND(H7>=1,I7>=1),\"Favorable\",IF(OR(H7<0.85,I7<0.85),\"Critical\",\"Watch\"))"
    },
    {
      "Reporting Period": "2027-01-31",
      "BAC": 5000000,
      "PV": 4250000,
      "EV": 3500000,
      "AC": 3200000,
      "CV": "=D8-E8",
      "SV": "=D8-C8",
      "CPI": "=IFERROR(D8/E8,0)",
      "SPI": "=IFERROR(D8/C8,0)",
      "EAC": "=IFERROR(B8/H8,B8)",
      "ETC": "=J8-E8",
      "VAC": "=B8-J8",
      "TCPI": "=IFERROR((B8-D8)/(B8-E8),0)",
      "Interpretation": "=IF(AND(H8>=1,I8>=1),\"Favorable\",IF(OR(H8<0.85,I8<0.85),\"Critical\",\"Watch\"))"
    },
    {
      "Reporting Period": "2027-02-28",
      "BAC": 5000000,
      "PV": 5000000,
      "EV": 5000000,
      "AC": 4700000,
      "CV": "=D9-E9",
      "SV": "=D9-C9",
      "CPI": "=IFERROR(D9/E9,0)",
      "SPI": "=IFERROR(D9/C9,0)",
      "EAC": "=IFERROR(B9/H9,B9)",
      "ETC": "=J9-E9",
      "VAC": "=B9-J9",
      "TCPI": "=IFERROR((B9-D9)/(B9-E9),0)",
      "Interpretation": "=IF(AND(H9>=1,I9>=1),\"Favorable\",IF(OR(H9<0.85,I9<0.85),\"Critical\",\"Watch\"))"
    }
  ],
  "Risk Register": [
    {
      "Risk ID": "R001",
      "Risk Category": "Technical",
      "Risk Description": "Integration delays",
      "Cause": "External dependencies",
      "Consequence": "Schedule delay",
      "Probability": 4,
      "Impact": 4,
      "Risk Score": "=F4*G4",
      "Risk Level": "=IF(H4>=20,\"Critical\",IF(H4>=12,\"High\",IF(H4>=6,\"Medium\",\"Low\")))",
      "Risk Owner": "Technical Lead",
      "Mitigation Action": "Early interface testing",
      "Contingency Action": "Escalate dependency",
      "Target Date": "2026-12-15",
      "Status": "Open",
      "Residual Probability": 2,
      "Residual Impact": 3,
      "Residual Risk": "=O4*P4",
      "Last Review": "2026-11-20",
      "Next Review": "2026-12-05",
      "Notes": null
    },
    {
      "Risk ID": "R002",
      "Risk Category": "Procurement",
      "Risk Description": "Vendor delivery delay",
      "Cause": "Procurement lead time",
      "Consequence": "Cost/schedule impact",
      "Probability": 3,
      "Impact": 4,
      "Risk Score": "=F5*G5",
      "Risk Level": "=IF(H5>=20,\"Critical\",IF(H5>=12,\"High\",IF(H5>=6,\"Medium\",\"Low\")))",
      "Risk Owner": "Procurement",
      "Mitigation Action": "Early purchase orders",
      "Contingency Action": "Alternative supplier",
      "Target Date": "2027-01-10",
      "Status": "Monitoring",
      "Residual Probability": 2,
      "Residual Impact": 3,
      "Residual Risk": "=O5*P5",
      "Last Review": "2026-11-20",
      "Next Review": "2026-12-15",
      "Notes": "High attention"
    },
    {
      "Risk ID": "R003",
      "Risk Category": "Change",
      "Risk Description": "Scope expansion",
      "Cause": "New requirements",
      "Consequence": "Budget overrun",
      "Probability": 4,
      "Impact": 5,
      "Risk Score": "=F6*G6",
      "Risk Level": "=IF(H6>=20,\"Critical\",IF(H6>=12,\"High\",IF(H6>=6,\"Medium\",\"Low\")))",
      "Risk Owner": "Project Manager",
      "Mitigation Action": "Change control board",
      "Contingency Action": "Defer low-priority scope",
      "Target Date": "2026-12-20",
      "Status": "Open",
      "Residual Probability": 2,
      "Residual Impact": 4,
      "Residual Risk": "=O6*P6",
      "Last Review": "2026-11-20",
      "Next Review": "2026-12-10",
      "Notes": null
    }
  ],
  "Issue Register": [
    {
      "Issue ID": "I001",
      "Date Raised": "2026-11-10",
      "Issue Description": "API dependency not available",
      "Category": "Technical",
      "Priority": "High",
      "Impact": "Schedule",
      "Responsible Person": "Technical Lead",
      "Due Date": "2026-12-01",
      "Status": "In Progress",
      "Root Cause": "External dependency",
      "Corrective Action": "Daily coordination",
      "Resolution": null,
      "Date Closed": null,
      "Days Open": "=IF(I4=\"Closed\",M4-B4,TODAY()-B4)",
      "Escalation Required": "Yes"
    },
    {
      "Issue ID": "I002",
      "Date Raised": "2026-11-18",
      "Issue Description": "Budget approval pending",
      "Category": "Finance",
      "Priority": "High",
      "Impact": "Cost",
      "Responsible Person": "Finance Lead",
      "Due Date": "2026-11-30",
      "Status": "Open",
      "Root Cause": "Approval cycle",
      "Corrective Action": "Escalate approval",
      "Resolution": null,
      "Date Closed": null,
      "Days Open": "=IF(I5=\"Closed\",M5-B5,TODAY()-B5)",
      "Escalation Required": "Yes"
    }
  ],
  "Change Management": [
    {
      "Change ID": "CR001",
      "Request Date": "2026-11-12",
      "Requested By": "Client",
      "Description": "Add reporting module",
      "Reason": "Management requirement",
      "Category": "Scope",
      "Priority": "High",
      "Cost Impact": 250000,
      "Schedule Impact (days)": 10,
      "Resource Impact": "Medium",
      "Risk Impact": "High",
      "Approval Status": "Under Review",
      "Approved By": null,
      "Approval Date": null,
      "Implementation Status": "Submitted",
      "Implementation Date": null
    },
    {
      "Change ID": "CR002",
      "Request Date": "2026-11-20",
      "Requested By": "Technical Lead",
      "Description": "Security enhancement",
      "Reason": "Risk mitigation",
      "Category": "Technical",
      "Priority": "High",
      "Cost Impact": 150000,
      "Schedule Impact (days)": 5,
      "Resource Impact": "Low",
      "Risk Impact": "High",
      "Approval Status": "Approved",
      "Approved By": "Project Sponsor",
      "Approval Date": "2026-11-25",
      "Implementation Status": "Approved",
      "Implementation Date": null
    }
  ],
  "Milestone Tracker": [
    {
      "Milestone ID": "M001",
      "Milestone": "Project Charter Approved",
      "WBS": "1",
      "Planned Date": "2026-09-10",
      "Forecast Date": "2026-09-10",
      "Actual Date": "2026-09-10",
      "Status": "Completed",
      "Days Variance": "=IF(F4<>\"\",F4-D4,E4-D4)",
      "Responsible Person": "Project Manager",
      "Critical?": "Yes",
      "Notes": null
    },
    {
      "Milestone ID": "M002",
      "Milestone": "Architecture Approved",
      "WBS": "2",
      "Planned Date": "2026-10-20",
      "Forecast Date": "2026-10-25",
      "Actual Date": null,
      "Status": "Delayed",
      "Days Variance": "=IF(F5<>\"\",F5-D5,E5-D5)",
      "Responsible Person": "Technical Lead",
      "Critical?": "Yes",
      "Notes": "Dependency delay"
    },
    {
      "Milestone ID": "M003",
      "Milestone": "Development Complete",
      "WBS": "3",
      "Planned Date": "2027-01-15",
      "Forecast Date": "2027-01-25",
      "Actual Date": null,
      "Status": "At Risk",
      "Days Variance": "=IF(F6<>\"\",F6-D6,E6-D6)",
      "Responsible Person": "Software Lead",
      "Critical?": "Yes",
      "Notes": null
    },
    {
      "Milestone ID": "M004",
      "Milestone": "Production Deployment",
      "WBS": "4",
      "Planned Date": "2027-02-15",
      "Forecast Date": "2027-02-20",
      "Actual Date": null,
      "Status": "At Risk",
      "Days Variance": "=IF(F7<>\"\",F7-D7,E7-D7)",
      "Responsible Person": "Infrastructure Lead",
      "Critical?": "Yes",
      "Notes": null
    }
  ],
  "Decision Log": [
    {
      "Action ID": "A001",
      "Date": "2026-11-25",
      "Meeting": "Steering Committee",
      "Decision/Action": "Approve security enhancement",
      "Responsible Person": "Project Sponsor",
      "Priority": "High",
      "Due Date": "2026-12-05",
      "Status": "Open",
      "Days Remaining": "=IF(H4=\"Closed\",0,G4-TODAY())",
      "Escalation": "Yes",
      "Comments": null
    },
    {
      "Action ID": "A002",
      "Date": "2026-11-25",
      "Meeting": "Project Review",
      "Decision/Action": "Resolve API dependency",
      "Responsible Person": "Technical Lead",
      "Priority": "Critical",
      "Due Date": "2026-12-01",
      "Status": "In Progress",
      "Days Remaining": "=IF(H5=\"Closed\",0,G5-TODAY())",
      "Escalation": "Yes",
      "Comments": null
    }
  ],
  "Project Charter": {
    "Project Title": "Digital Service & High-Tech Incubation Project 2026",
    "Implementing Institution": "Ministry of Innovation and Technology (MInT), Ethiopia",
    "Donor": "Government of Italy",
    "Supervising Agency": "Italian Agency for Development Cooperation (AICS)",
    "Project Type": "Digital Transformation / E-Government / High-Technology Innovation / Startup Incubation",
    "Geographic Scope": "Ethiopia",
    "Project Description": "Integrated strengthening of digital services and creation of a high-technology innovation incubation ecosystem.",
    "Strategic Objective": "Strengthen digital public services and enable high-technology innovation enterprises through incubation, capacity building, technology enablement and enterprise support.",
    "Start Date": "2026-09-01",
    "Planned Finish Date": "2029-08-31",
    "Approved Budget": "#VALUE!",
    "Project Priority": "High",
    "Project Phase": "Implementation",
    "Reporting Frequency": "Weekly / Monthly"
  }
};
